### ISSUE TITLE
We can add an order without assigning a customer

### ISSUE THREAD

**Issue by alunibern** [scg-unibe-ch/ese2017-team1#2]
_Go to /orderForm. No question about the customer is made and you can pass an order without assigning a customer._
* Same reason as with issue 1 above.

**Comment by aurorra** [comment]
The product is now assigned to a client but we have a whitelabel error when we haven't added a new client on the previous page (see Issue 6). 

Problem: We can not select a client yet, only create a new one and assign a product to this client. Working on it.

**Comment by aurorra** [comment]
Issue solved, but issue 6 remains.
