### ISSUE TITLE
Call /jobs and expect a list of jobs

### ISSUE THREAD

**Issue by alunibern** [scg-unibe-ch/ese2017-team1#4]
_Get /jobs and expect a list of jobs._
* Fails, `java.lang.NullPointerException: null
	at hello.MainController.listProductOrders(MainController.java:34) ~[classes/:na]`
* Reason: `List <> listAllJobs()`  doesn't work with CrudRepository, try using JpaRepository 'findAll()'

**Comment by aneahgi** [comment]
i think we don't really use jobs anymore. but not really sure. teammates, what do you think?

**Comment by aurorra** [comment]
We created jobs.html in order to show the open jobs in the database. Since we now use the file showJobs.html for this I don't think we need that file anymore.

**Comment by aneahgi** [comment]
ok i deleted it, we really didn't used it anymore =)
